---
title: "Productivity vs Hourly Compensation"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

<!--
## Data
-->

```{r, load, echo = FALSE}
load("./prod_wage_RData")
# str(prod_wage)
```

## Plots

### 순생산성과 시간당 보수

```{r, plot1, echo = FALSE, fig.width = 8, fig.height = 6}
par(family = "HCR Dotum LVT")
main_title <- "생산성과 시간당 보수(1948-2014)"
x_lab <- "연도"
y_lab <- "1948년 이래 누적된 변화(%)"
text_lab <- c("시간당 보수", "생산성")
legend_lab <- c("1948-1973\n생산성 : 96.7%\n시간당 보수 : 91.3%", "1973-2014\n생산성 : 72.2%\n시간당 보수 : 9.2%")
plot(Net_productivity ~ Year, data = prod_wage, type = "l", col = "blue", xlab = x_lab, ylab = y_lab, main = main_title, lwd = 5, ylim = c(-50, 300), las = 1)
lines(Hourly_compensation ~ Year, data = prod_wage, col = "cyan", lwd = 5)
abline(h = seq(-50, 300, by = 50), lty = 3)
abline(v = 1973, lty = 3)
# legend(x = 1948, y = 290, legend = c("생산성", "보수"), lty = 1, col = c("blue", "cyan"), lwd = 3:2, bty = "n")
n_rows <- nrow(prod_wage)
# points(Net_productivity[n_rows] ~ Year[n_rows], data = prod_wage, pch = 21, col = "blue", bg = "blue", cex = 1.2)
# points(Hourly_compensation[n_rows] ~ Year[n_rows], data = prod_wage, pch = 21, col = "cyan", bg = "cyan", cex = 1.2)
# xend <- prod_wage$Year[n_rows]
# yend_p <- prod_wage$Net_productivity[n_rows]
# yend_w <- prod_wage$Hourly_compensation[n_rows]
end_df <- subset(prod_wage, Year == Year[n_rows])
y_1995df <- subset(prod_wage, Year == 1995)
points(x = rep(end_df[, 1], 2), y = end_df[, 3:2], pch = 21, col = c("blue", "cyan"), bg = c("blue", "cyan"), cex = 1.3)
text(x = 1995, y = y_1995df[, 2:3], labels = text_lab, pos = 1, 3)
text(x = 2014, y = end_df[, 2:3], labels = paste(format(end_df[, 2:3], digits = 1, nsmall = 1), "%", sep = ""), pos = 3)
text(x = c(1955, 1974), y = 225, labels = legend_lab, adj = 0)
dev.copy(png, file ="../pics/Productivity_vs_Wages_kr.png", width = 640, height = 480)
```

<P style = "page-break-before:always"/>

### 순생산성과 평균 시간당 보수 및 중위 시간당 보수

```{r, plot2, echo = FALSE, fig.width = 8, fig.height = 6}
par(family = "HCR Dotum LVT")
main_title_2 <- "생산성과 평균 보수 및 중위 보수(1973-2014)"
y_lab_2 <- "1973년 이래 누적된 변화(%)"
text_lab_2 <- c("(순)생산성", "평균\n시간당 보수", "중위\n시간당 보수")
plot(Net_productivity ~ Year, data = prod_wage_2, type = "l", col = "blue", xlab = x_lab, ylab = y_lab_2, main = main_title_2, lwd = 5, xlim = c(1973, 2018), ylim = c(-5, 80), las = 1)
lines(Real_average_hourly_compensation ~ Year, data = prod_wage_2, col = "deepskyblue", lwd = 5)
lines(Real_median_hourly_compensation ~ Year, data = prod_wage_2, col = "cyan", lwd = 5)
abline(h = seq(0, 80, by = 20), lty = 3)
# legend(x = 1973, y = 75, legend = c("(순)생산성", "평균 보수", "중위 보수"), lty = 1, col = c("blue", "deepskyblue", "cyan"), lwd = 5, bty = "n")
n_rows_2 <- nrow(prod_wage_2)
# points(Net_productivity[n_rows] ~ Year[n_rows], data = prod_wage, pch = 21, col = "blue", bg = "blue", cex = 1.2)
# points(Hourly_compensation[n_rows] ~ Year[n_rows], data = prod_wage, pch = 21, col = "cyan", bg = "cyan", cex = 1.2)
# xend_2 <-prod_wage_2$Year[n_rows_2]
# yend_2.p <- prod_wage_2$Net_productivity[n_rows_2]
# yend_2.a <- prod_wage_2$Real_average_hourly_compensation[n_rows_2]
# yend_2.m <- prod_wage_2$Real_median_hourly_compensation[n_rows_2]
end_df_2 <- subset(prod_wage_2, Year == Year[n_rows_2])
y2007_df <- subset(prod_wage_2, Year == 2007)
points(x = rep(end_df_2[, 1], 3), y = end_df_2[, 4:2], pch = 21, col = c("blue", "deepskyblue", "cyan"), bg = c("blue", "deepskyblue", "cyan"), cex = 1.3)
text(x = 2007, y = y2007_df[, 4:2] - c(3, 3, 0), labels = text_lab_2, pos = 1)
text(x = end_df_2[, 1], y = end_df_2[, 4:2], labels = paste(end_df_2[, 4:2], "%", sep = ""), pos = 4)
dev.copy(png, file ="../pics/Productivity_vs_median_Wages_kr.png", width = 640, height = 480)
```

<!--
### Save

```{r, save, echo = FALSE}
save.image("./prod_wage_add.RData")
```
-->